### ISSUE TITLE
Simulating digit

### ISSUE THREAD

**Issue by b4be1** [facebookresearch/digit-interface#1]
I was curious if there are any ways to simulate the digit sensor. E.g., in pybullet or Coppelia?

**Comment by robertocalandra** [comment]
We do not currently have code for that, but it is in theory possible to create a simulator. (e.g., see http://wordpress.csc.liv.ac.uk/smartlab/wp-content/uploads/sites/5/2019/06/ICRA2019ViTac_paper_8.pdf)

**Comment by NileshArnaiya** [comment]
Similar - https://github.com/facebookresearch/tacto
