### ISSUE TITLE
get_frame() function issue

### ISSUE THREAD

**Issue by Ahmad-Wajid** [facebookresearch/digit-interface#16]
Currently having an issue with DIGIT, when saving through the DIGIT view, the image is fine, however, when using the built-in get_frame() function, the resulting matrix (ndarray) has zeros for every red and blue entry, meaning the output image is entirely green as shown below. Any insight is greatly appreciated.
![Digit View D20740_screenshot_23 01 2024](https://github.com/facebookresearch/digit-interface/assets/135176225/a9af5b48-22c5-4d50-8de2-08055b25e4a9)
![digit_image0](https://github.com/facebookresearch/digit-interface/assets/135176225/ca3c9654-ae3a-4707-acf7-18a537e7e612)

**Comment by robertocalandra** [comment]
Hi @Ahmad1285,
I don't remember seeing this issue before.  

@AlphaBetaPhi any thoughts?

**Comment by JuliaDi** [comment]
For anyone else who has this issue, we saw this issue before if you are calling the first frame from the DIGIT. If you throw out the initial frames and call a subsequent frame, then the image will be correct.
