### ISSUE TITLE
Set intensity of LEDs independently

### ISSUE THREAD

**Issue by lzyplayer** [facebookresearch/digit-interface#2]
Thanks for sharing such awsome work!
I have found the intensity setting function in `digit.py`.
wonder is there a way to set intensity of LEDs independtly?

**Comment by AlphaBetaPhi** [comment]
Hi @lzyplayer,

Thank you for your interest in `digit-interface`. The currently released DIGIT firmware does not support independent control of each LED. 

Is this something you would be interested in?

**Comment by lzyplayer** [comment]
Thanks for the reply! 
Since DIGIT got 5 LED slots while LED only have 3 colors, it would be really useful if we can set the LED independtly and obtain images under all 5 different light direction.

**Comment by AlphaBetaPhi** [comment]
Hi @lzyplayer,

Thank you, this is valuable feedback!

**Comment by lzyplayer** [comment]
Hi @AlphaBetaPhi ,
Thanks for recently update! I have assembly serverl DIGITs, which all works fine. However, setting LED intensity in Digit-interface seems not working, resulting in too strong light on image. Here's a image while I'm pressing DIGIT against a plastic ball. 
<img src="https://user-images.githubusercontent.com/20348451/89181614-b24f3e00-d5c6-11ea-8799-993a0daa1f5a.png" height="200px">
Below are logs while setting LED, and LEDs remains the brightest status.
```python
>>> digit.set_intensity(20)
DEBUG:digit_interface.digit:D00045:LED intensity set to 20
20
>>> time.sleep(1)
>>> # Change LED illumination intensity
... 
>>> digit.set_intensity(1)
DEBUG:digit_interface.digit:D00045:LED intensity set to 1
1
```
Addtionally, It seems a little lost of focus.
Thanks for any reply~

**Comment by lzyplayer** [comment]
Could I reopen this issue?

**Comment by AlphaBetaPhi** [comment]
Hi @lzyplayer, could we connect offline to troubleshoot? My email is: lambetam[at]fb[dot]com

**Comment by AlphaBetaPhi** [comment]
Hi @lzyplayer, 

We have released the beta firmware to production for version 2.00 of the DIGIT firmware to address this issue.

Thank you for your support.

**Comment by lzyplayer** [comment]
Thank you for your great work!
