### ISSUE TITLE
Image noise

### ISSUE THREAD

**Issue by lzyplayer** [facebookresearch/digit-interface#4]
I have finished assembly a DIGIT PCB part. Here's what I got
<img src="https://user-images.githubusercontent.com/20348451/88532774-c380d380-d037-11ea-9167-2ae9eb9cda45.jpeg" height="300px">
After flashing the firmwire, I was able to get status of DIGIT. However the image I got is a little wired which seems too noisy. I have tried different resolution and stream mode, bot none of them help.
here's image I got:
<img src="https://user-images.githubusercontent.com/20348451/88533300-a7316680-d038-11ea-902b-737d4d47f51e.png" height="300px">
logs:
```bash
>>> # Connect to a Digit device with serial number with friendly name
... 
>>> digit = Digit("DXXXXX", "Left Gripper")
DEBUG:digit_interface.digit:Digit object constructed with serial DXXXXX
DEBUG:digit_interface.digit_handler:Finding udev devices with subsystem=video4linux, id_model=DIGIT
DEBUG:digit_interface.digit_handler:Following udev devices found: 
DEBUG:digit_interface.digit_handler:Device('/sys/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.0/video4linux/video1')
DEBUG:digit_interface.digit_handler:Searching for DIGIT with serial number DXXXXX
>>> 
>>> digit.connect()
INFO:digit_interface.digit:DXXXXX:Connecting to DIGIT
INFO:digit_interface.digit:DXXXXX:Setting stream defaults to QVGA, 60fps, maximum LED intensity.
DEBUG:digit_interface.digit:Default stream to QVGA {'width': 320, 'height': 240}
DEBUG:digit_interface.digit:DXXXXX:Stream resolution set to 240w x 320h
DEBUG:digit_interface.digit:Default stream with 60 fps
DEBUG:digit_interface.digit:DXXXXX:Stream FPS set to 60
DEBUG:digit_interface.digit:Setting maximum LED illumination intensity
DEBUG:digit_interface.digit:DXXXXX:LED intensity set to 255
>>> # Print device info
... 
>>> print(digit.info())
Name: Left Gripper /dev/video1
        - Model: DIGIT
        - Revision: 0101
        - CV Device?: True
        - Connected?: True
Stream Info:
        - Resolution: 320 x 240
        - FPS: 60
        - LED Intensity: 255
```
Is there something wrong with my cam?
Thanks for any reply!

**Comment by AlphaBetaPhi** [comment]
@lzyplayer, great work!

Did you hand assemble the DIGIT main PCB?

This appears to be an issue an issue with one or more of the ball grid pads on the camera not being soldered to the main PCB.    I have seen this a few times on some early prototypes. 

I would suggest the following:
- if you have access to an X-Ray machine, image the DIGIT main PCB and observe the ball grid soldering points.
- remove camera, clean area, re-apply solder to ball grid array on PCB and on camera, apply a generous amount of tack flux, heat with rework station and observe the camera locking into place by surface tension of the bga array.

**Comment by lzyplayer** [comment]
@AlphaBetaPhi , Thanks for your professional advice!
DIGIT‘s main PCB is printed and assembled by online SMT service order. I have only done the firmware flashing part. I will convey your advice to manufacturer and try some rework!

**Comment by lzyplayer** [comment]
reworking... Close issue for now.

**Comment by lzyplayer** [comment]
@AlphaBetaPhi , it worked! Thanks again for your kind support!
After reworking accroding to your advice, DIGIT is able to get reasonable image. However, some vertical image noise remains. The higher the exposure, the higher the noise. 
Have you ever run into this problem? Or is there some way to set exposure or ISO for camera?
Left: low exposure  Right: high exposure
<img src="https://user-images.githubusercontent.com/20348451/88774508-20a29380-d1b6-11ea-9e01-4aa99353b5ee.png" height="400px"><img src="https://user-images.githubusercontent.com/20348451/88774515-239d8400-d1b6-11ea-9890-0aec3e31aa37.png" height="400px">

**Comment by AlphaBetaPhi** [comment]
Hi @lzyplayer, 

This is expected, we have set set the camera properties for use within the 3D printed enclosure with illumination from the perimeter lighting. 

There are plans to enable control of camera properties for finer tuning in later firmware releases.

**Comment by lzyplayer** [comment]
Got it! Thank you for sharing such great work and providing such generous help! XD
