### ISSUE TITLE
Windows issue

### ISSUE THREAD

**Issue by Rudy112** [facebookresearch/digit-interface#9]
Hi there,

When I try to run the demo code you provided, there is an error "ModuleNotFoundError: No module named 'fcntl'". I searched that this module is only available on UNIX-based PC. 

Do you know how to solve it?

Thanks a lot!

**Comment by AlphaBetaPhi** [comment]
Hi @Rudy112,

Thank you for your interest in the project. At this moment, linux based OS's are only supported.

If you'd like to connect with Windows, you connect with the following:

```
import cv2

VIDEO_DEV = 0 # change to your video device id

digit_dev = cv2.VideoCapture(VIDEO_DEV)
ret, frame = digit_dev.read() # ret is the return status indicating successful frame capture, frame contains the image from sensor
```

For future support: are you running ROS and other platforms as well on a Windows based machine? Or are you just evaluating the output of the sensor?

**Comment by Rudy112** [comment]
> Hi @Rudy112,
> 
> Thank you for your interest in the project. At this moment, linux based OS's are only supported.
> 
> If you'd like to connect with Windows, you connect with the following:
> 
> ```
> import cv2
> 
> VIDEO_DEV = 0 # change to your video device id
> 
> digit_dev = cv2.VideoCapture(VIDEO_DEV)
> ret, frame = digit_dev.read() # ret is the return status indicating successful frame capture, frame contains the image from sensor
> ```
> 
> For future support: are you running ROS and other platforms as well on a Windows based machine? Or are you just evaluating the output of the sensor?

Hi @AlphaBetaPhi , Thanks for your replying.

Currently, I am trying to evaluate the output based machine. I have tried on linux system and it works well. In the future, I may use it under ROS.
